# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LDHData": "LDHData.ipynb",
         "LDHDataModule": "LDHData.ipynb",
         "DEFAULT_TOKENIZER": "LDHData.ipynb",
         "LightningReapp": "LightningReapp.ipynb",
         "KFoldTrainer": "Trainers.ipynb",
         "cross_validate": "Trainers.ipynb"}

modules = ["ldhdata.py",
           "lightningreapp.py",
           "trainers.py"]

doc_url = "https://danielcpham.github.io/reappraisalmodel/"

git_url = "https://github.com/danielcpham/reappraisalmodel/tree/main/"

def custom_doc_links(name): return None
